spring:
  kafka:
    bootstrap-servers: kafka:9092
    streams:
      application-id: health-stream-processor
      bootstrap-servers: kafka:9092
      num-threads: 2
      commit-interval-ms: 1000
      properties:
        auto.offset.reset: earliest
      auto-startup: true
      

kafka:
  topics:
    input: sensor_raw
    output: processed_data

logging:
  level:
    com.stream.processor: DEBUG
    org.apache.kafka: INFO
